version: '3'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Optional: Mount SSL certificates if needed
      # - ./certs:/app/certs
      # Optional: For development, you can mount the code directory
      # - .:/app 